<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AABLR0394" ignored="0" name="Test" tests="8" failures="1" timestamp="03 May 2020 12:44:16 GMT" time="149.102" errors="0">
  <testcase name="loginToApplication" time="9.687" classname="com.postman.qa.testcases.WorkspaceTests"/>
  <testcase name="createWorkspaceFromDashboard" time="38.055" classname="com.postman.qa.testcases.WorkspaceTests"/>
  <testcase name="updateWorkspaceCreated" time="42.747" classname="com.postman.qa.testcases.WorkspaceTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Cancel during Update operation is unsuccessful expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Cancel during Update operation is unsuccessful expected [true] but found [false]
at com.postman.qa.testcases.WorkspaceTests.updateWorkspaceCreated(WorkspaceTests.java:84)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- updateWorkspaceCreated -->
  <testcase name="deleteWorkspaceCreated" time="37.809" classname="com.postman.qa.testcases.WorkspaceTests"/>
  <testcase name="createWorkspaceFromDropDown" time="6.376" classname="com.postman.qa.testcases.WorkspaceTests"/>
  <testcase name="createDuplicateWorkspace" time="7.141" classname="com.postman.qa.testcases.WorkspaceTests"/>
  <testcase name="cancelDeleteWS" time="0.0" classname="com.postman.qa.testcases.WorkspaceTests"/>
  <testcase name="cancelWCreateS" time="0.001" classname="com.postman.qa.testcases.WorkspaceTests"/>
</testsuite> <!-- Test -->
